version: '3.8'
services:
  controller:
    image: ngrinder/controller:3.5.5
    restart: always
    ports:
      - "9000:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
  ngrinder-agent:
    image: ngrinder/agent:3.5.5
    restart: always
    links:
      - controller
